# declare constants
INDEX = 'INDEX'
FNAME = 'FNAME'
EXPOSURE = 'EXPOSURE'
EXPSTART = 'EXPSTART'
EXPSTARTJDD = 'EXPSTARTJDD'

GAIN = 'GAIN'
OFFSET = 'OFFSET'
PIXSIZE = 'PIXSIZE'
CAMERA = 'CAMERA'
CCDTEMP = 'CCDTEMP'
CCDSETTEMP = 'CCDSETTEMP'
BAYERPAT = 'BAYER'
TELESCOPE = 'TELESCOP'
FOCALLENGTH = 'FOCALLENGTH'
FOCRATIO = 'FOCRATIO'
RA = 'RA'
DEC = 'DEC'
ALTITUDE = 'ALTITUDE'
AZIMUTH = 'AZIMUTH'
AIRMASS = 'AIRMASS'
PIERSIDE = 'PIERSIDE'
SITELAT = 'SITELAT'
SITELONG = 'SITELONG'
SITEELEV = 'SITEELEV'
FILTER = 'FILTER'
OBJECT = 'OBJECT'
ROTATION = 'ROTATION'
FOCUSERPOS = 'FOCUSERPOS'
FOCUSERTEMP = 'FOCUSTEMP'
DEWPOINT = 'DEWPOINT'
HUMIDITY = 'HUMIDITY'
PRESSURE = 'PRESSURE'
AMBIENTTEMP = 'AMBIENTTEMP'
WINDDIR = 'WINDDIR'
WINDSPD = 'WINDSPD'

RMSRA = 'RMS(RA)'
RMSDEC = 'RMS(DEC)'
RMS = 'RMS'
HFR = 'HFR'
FWHM = 'FWHM'
Eccentricity = 'Eccentricity'
HFRStDev = 'HFRStDev'
DetectedStars = 'DetectedStars'
ADUMean = 'ADUMean'
ADUMedian = 'ADUMedian'
ADUMin = 'ADUMin'
ADUMax = 'ADUMax'
GUIDINGPIXRA = 'GUIDINGRA(PIX)'
GUIDINGPIXDEC = 'GUIDINGDEC(PIX)'
GUIDINGPIX = 'GUIDING(PIX)'
GUIDINGMINRA = 'GUIDING(MINRA)'
GUIDINGMAXRA = 'GUIDING(MAXRA)'
GUIDINGMINDEC = 'GUIDING(MINDEC)'
GUIDINGMAXDEC = 'GUIDING(MAXDEC)'
GUIDINGPEAKSRA = 'GUIDINGPEAKS(RA)'
GUIDINGPEAKSDEC = 'GUIDINGPEAKS(DEC)'
GUIDINGMINSNR = 'GUIDING(MINSNR)'
GUIDINGMAXSNR = 'GUIDING(MAXSNR)'
GUIDINGRMSSNR = 'GUIDING(RMSSNR)'
GUIDINGMINSTARMASS = 'GUIDING(MINSTARMASS)'
MOONALT = 'MOONALT'
SUNALT = 'SUNALT'


Columns = [INDEX, FNAME, EXPSTART, EXPOSURE, GAIN, OFFSET, PIXSIZE, CAMERA,
           CCDTEMP, CCDSETTEMP, BAYERPAT, TELESCOPE, FOCALLENGTH, FOCRATIO,
           RA, DEC, AZIMUTH, ALTITUDE, AIRMASS, PIERSIDE,
           SITELONG, SITELAT, FILTER, OBJECT, ROTATION,
           HFR, HFRStDev, DetectedStars, ADUMean, ADUMedian, ADUMin, ADUMax,
           FWHM, Eccentricity,
           FOCUSERPOS, DEWPOINT, HUMIDITY, PRESSURE,
           AMBIENTTEMP, WINDDIR, WINDSPD]

# GuidingRMS  GuidingRMSArcSec  GuidingRMSRA  GuidingRMSRAArcSec  GuidingRMSDEC  GuidingRMSDECArcSec