[tool.pytest.ini_options]
pythonpath = [
    "src",
]
testpaths = [
    "test",
]
addopts = [
    "--import-mode=importlib",
]

[tool.flake8]
max-line-length=127
exclude = [
    ".git",
    "__pycache__",
]